name: generate animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"  # Run at midnight every day

  # Allows to manually run the job at any time
  workflow_dispatch:

  # Run on every push to the master branch
  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate GitHub Contribution Grid Snake Animation
        uses: Platane/snk/svg-only@v3  # Assuming this version exists
        with:
          github_user_name: tunaarikaya  # Replace with your username
          outputs: |
            dist/github-contribution-grid-snake.svg  # Light theme output path
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark  # Dark theme output path
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push GitHub Contribution Grid Snake SVGs to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output  # Output branch name
          build_dir: dist         # Directory containing generated SVGs
          commit_message: "Automated update of contribution grid snake animation"  # Optional commit message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
